// Code generated by protoc-gen-go.
// source: phonebook.proto
// DO NOT EDIT!

/*
Package phonebook is a generated protocol buffer package.

It is generated from these files:
	phonebook.proto

It has these top-level messages:
	Contact
	PhoneNumber
*/
package phonebook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneNumber_PhoneType int32

const (
	PhoneNumber_MOBILE PhoneNumber_PhoneType = 0
	PhoneNumber_HOME   PhoneNumber_PhoneType = 1
	PhoneNumber_WORK   PhoneNumber_PhoneType = 2
)

var PhoneNumber_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var PhoneNumber_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneNumber_PhoneType) String() string {
	return proto.EnumName(PhoneNumber_PhoneType_name, int32(x))
}
func (PhoneNumber_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Contact struct {
	Name        string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email       string         `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNumber []*PhoneNumber `protobuf:"bytes,3,rep,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetPhoneNumber() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type PhoneNumber struct {
	Number string                `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   PhoneNumber_PhoneType `protobuf:"varint,2,opt,name=type,enum=phonebook.PhoneNumber_PhoneType" json:"type,omitempty"`
}

func (m *PhoneNumber) Reset()                    { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()               {}
func (*PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneNumber_PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneNumber_MOBILE
}

func init() {
	proto.RegisterType((*Contact)(nil), "phonebook.Contact")
	proto.RegisterType((*PhoneNumber)(nil), "phonebook.PhoneNumber")
	proto.RegisterEnum("phonebook.PhoneNumber_PhoneType", PhoneNumber_PhoneType_name, PhoneNumber_PhoneType_value)
}

func init() { proto.RegisterFile("phonebook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0xc8, 0xcf,
	0x4b, 0x4d, 0xca, 0xcf, 0xcf, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xe5, 0x71, 0xb1, 0x3b, 0xe7, 0xe7, 0x95, 0x24, 0x26, 0x97, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9,
	0xb9, 0x89, 0x99, 0x39, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0xc8, 0x92, 0x8b, 0x07, 0x6c, 0x42,
	0x7c, 0x5e, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x98, 0x1e,
	0xc2, 0x9e, 0x00, 0x10, 0xcb, 0x0f, 0x2c, 0x1b, 0xc4, 0x5d, 0x80, 0xe0, 0x28, 0x75, 0x30, 0x72,
	0x71, 0x23, 0x49, 0x0a, 0x89, 0x71, 0xb1, 0x41, 0x0d, 0x81, 0x58, 0x0b, 0xe5, 0x09, 0x99, 0x70,
	0xb1, 0x94, 0x54, 0x16, 0xa4, 0x82, 0xed, 0xe5, 0x33, 0x52, 0xc0, 0x6e, 0x34, 0x84, 0x1d, 0x52,
	0x59, 0x90, 0x1a, 0x04, 0x56, 0xad, 0xa4, 0xcd, 0xc5, 0x09, 0x17, 0x12, 0xe2, 0xe2, 0x62, 0xf3,
	0xf5, 0x77, 0xf2, 0xf4, 0x71, 0x15, 0x60, 0x10, 0xe2, 0xe0, 0x62, 0xf1, 0xf0, 0xf7, 0x75, 0x15,
	0x60, 0x04, 0xb1, 0xc2, 0xfd, 0x83, 0xbc, 0x05, 0x98, 0x92, 0xd8, 0xc0, 0x81, 0x61, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x47, 0x0b, 0xff, 0x1f, 0x01, 0x00, 0x00,
}
