/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grpc_phonebook.Contact', null, global);
goog.exportSymbol('proto.grpc_phonebook.PhoneNumber', null, global);
goog.exportSymbol('proto.grpc_phonebook.PhoneNumber.PhoneType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_phonebook.Contact = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.grpc_phonebook.Contact.repeatedFields_, null);
};
goog.inherits(proto.grpc_phonebook.Contact, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_phonebook.Contact.displayName = 'proto.grpc_phonebook.Contact';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.grpc_phonebook.Contact.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_phonebook.Contact.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_phonebook.Contact.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_phonebook.Contact} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_phonebook.Contact.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    phoneNumberList: jspb.Message.toObjectList(msg.getPhoneNumberList(),
    proto.grpc_phonebook.PhoneNumber.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_phonebook.Contact}
 */
proto.grpc_phonebook.Contact.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_phonebook.Contact;
  return proto.grpc_phonebook.Contact.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_phonebook.Contact} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_phonebook.Contact}
 */
proto.grpc_phonebook.Contact.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = new proto.grpc_phonebook.PhoneNumber;
      reader.readMessage(value,proto.grpc_phonebook.PhoneNumber.deserializeBinaryFromReader);
      msg.addPhoneNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_phonebook.Contact.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_phonebook.Contact.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_phonebook.Contact} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_phonebook.Contact.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPhoneNumberList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.grpc_phonebook.PhoneNumber.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.grpc_phonebook.Contact.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc_phonebook.Contact.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.grpc_phonebook.Contact.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.grpc_phonebook.Contact.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated PhoneNumber phone_number = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.grpc_phonebook.PhoneNumber>}
 */
proto.grpc_phonebook.Contact.prototype.getPhoneNumberList = function() {
  return /** @type{!Array.<!proto.grpc_phonebook.PhoneNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.grpc_phonebook.PhoneNumber, 3));
};


/** @param {!Array.<!proto.grpc_phonebook.PhoneNumber>} value */
proto.grpc_phonebook.Contact.prototype.setPhoneNumberList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.grpc_phonebook.PhoneNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.grpc_phonebook.PhoneNumber}
 */
proto.grpc_phonebook.Contact.prototype.addPhoneNumber = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.grpc_phonebook.PhoneNumber, opt_index);
};


proto.grpc_phonebook.Contact.prototype.clearPhoneNumberList = function() {
  this.setPhoneNumberList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_phonebook.PhoneNumber = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_phonebook.PhoneNumber, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc_phonebook.PhoneNumber.displayName = 'proto.grpc_phonebook.PhoneNumber';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_phonebook.PhoneNumber.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_phonebook.PhoneNumber.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_phonebook.PhoneNumber} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc_phonebook.PhoneNumber.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_phonebook.PhoneNumber}
 */
proto.grpc_phonebook.PhoneNumber.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_phonebook.PhoneNumber;
  return proto.grpc_phonebook.PhoneNumber.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_phonebook.PhoneNumber} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_phonebook.PhoneNumber}
 */
proto.grpc_phonebook.PhoneNumber.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {!proto.grpc_phonebook.PhoneNumber.PhoneType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_phonebook.PhoneNumber.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_phonebook.PhoneNumber.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_phonebook.PhoneNumber} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc_phonebook.PhoneNumber.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.grpc_phonebook.PhoneNumber.PhoneType = {
  MOBILE: 0,
  HOME: 1,
  WORK: 2
};

/**
 * optional string number = 1;
 * @return {string}
 */
proto.grpc_phonebook.PhoneNumber.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc_phonebook.PhoneNumber.prototype.setNumber = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional PhoneType type = 2;
 * @return {!proto.grpc_phonebook.PhoneNumber.PhoneType}
 */
proto.grpc_phonebook.PhoneNumber.prototype.getType = function() {
  return /** @type {!proto.grpc_phonebook.PhoneNumber.PhoneType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.grpc_phonebook.PhoneNumber.PhoneType} value */
proto.grpc_phonebook.PhoneNumber.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.grpc_phonebook);
