// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	CreateContactReq
	CreateContactRes
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import phonebook "github.com/iheanyi/grpc-phonebook"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateContactReq struct {
	Name            string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email           string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNumber     string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	PhoneNumberType string `protobuf:"bytes,4,opt,name=phone_number_type,json=phoneNumberType" json:"phone_number_type,omitempty"`
}

func (m *CreateContactReq) Reset()                    { *m = CreateContactReq{} }
func (m *CreateContactReq) String() string            { return proto.CompactTextString(m) }
func (*CreateContactReq) ProtoMessage()               {}
func (*CreateContactReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateContactReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContactReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateContactReq) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateContactReq) GetPhoneNumberType() string {
	if m != nil {
		return m.PhoneNumberType
	}
	return ""
}

type CreateContactRes struct {
	Contact *phonebook.Contact `protobuf:"bytes,1,opt,name=contact" json:"contact,omitempty"`
}

func (m *CreateContactRes) Reset()                    { *m = CreateContactRes{} }
func (m *CreateContactRes) String() string            { return proto.CompactTextString(m) }
func (*CreateContactRes) ProtoMessage()               {}
func (*CreateContactRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateContactRes) GetContact() *phonebook.Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateContactReq)(nil), "api.CreateContactReq")
	proto.RegisterType((*CreateContactRes)(nil), "api.CreateContactRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PhoneBook service

type PhoneBookClient interface {
	CreateContact(ctx context.Context, in *CreateContactReq, opts ...grpc.CallOption) (*CreateContactRes, error)
}

type phoneBookClient struct {
	cc *grpc.ClientConn
}

func NewPhoneBookClient(cc *grpc.ClientConn) PhoneBookClient {
	return &phoneBookClient{cc}
}

func (c *phoneBookClient) CreateContact(ctx context.Context, in *CreateContactReq, opts ...grpc.CallOption) (*CreateContactRes, error) {
	out := new(CreateContactRes)
	err := grpc.Invoke(ctx, "/api.PhoneBook/CreateContact", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PhoneBook service

type PhoneBookServer interface {
	CreateContact(context.Context, *CreateContactReq) (*CreateContactRes, error)
}

func RegisterPhoneBookServer(s *grpc.Server, srv PhoneBookServer) {
	s.RegisterService(&_PhoneBook_serviceDesc, srv)
}

func _PhoneBook_CreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookServer).CreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PhoneBook/CreateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookServer).CreateContact(ctx, req.(*CreateContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PhoneBook",
	HandlerType: (*PhoneBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContact",
			Handler:    _PhoneBook_CreateContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0x03, 0x41,
	0x0c, 0x80, 0x59, 0x5b, 0x95, 0x4d, 0x15, 0x35, 0x28, 0x2c, 0x3d, 0x69, 0x4f, 0x22, 0x3a, 0x8b,
	0xf5, 0x2c, 0x88, 0xbd, 0x79, 0x10, 0x29, 0xde, 0xcb, 0xcc, 0x10, 0xba, 0x43, 0x9d, 0xc9, 0x38,
	0x9d, 0x1e, 0xf6, 0x19, 0x7c, 0x69, 0x69, 0x96, 0x6a, 0xfd, 0xb9, 0x25, 0x5f, 0xbe, 0x84, 0x24,
	0x50, 0xea, 0xe8, 0x54, 0x4c, 0x9c, 0x19, 0x7b, 0x3a, 0xba, 0xe1, 0xed, 0xdc, 0xe5, 0x66, 0x65,
	0x94, 0x65, 0x5f, 0xbb, 0x86, 0x74, 0x68, 0x5d, 0x3d, 0x4f, 0xd1, 0xde, 0xc4, 0x86, 0x03, 0x19,
	0xe6, 0x45, 0xfd, 0x15, 0x75, 0x7d, 0xa3, 0x8f, 0x02, 0x8e, 0x27, 0x89, 0x74, 0xa6, 0x09, 0x87,
	0xac, 0x6d, 0x9e, 0xd2, 0x3b, 0x22, 0xf4, 0x83, 0xf6, 0x54, 0x15, 0xe7, 0xc5, 0x65, 0x39, 0x95,
	0x18, 0x4f, 0x61, 0x97, 0xbc, 0x76, 0x6f, 0xd5, 0x8e, 0xc0, 0x2e, 0xc1, 0x0b, 0x38, 0x90, 0x89,
	0xb3, 0xb0, 0xf2, 0x86, 0x52, 0xd5, 0x93, 0xe2, 0x40, 0xd8, 0xb3, 0x20, 0xbc, 0x82, 0x93, 0x6d,
	0x65, 0x96, 0xdb, 0x48, 0x55, 0x5f, 0xbc, 0xa3, 0x2d, 0xef, 0xb5, 0x8d, 0x34, 0x7a, 0xf8, 0xb3,
	0xcc, 0x12, 0xaf, 0x61, 0xdf, 0x76, 0x99, 0xec, 0x33, 0x18, 0xa3, 0xfa, 0x3e, 0x62, 0xe3, 0x6d,
	0x94, 0xf1, 0x13, 0x94, 0x2f, 0xeb, 0xea, 0x23, 0xf3, 0x02, 0xef, 0xe1, 0xf0, 0xc7, 0x38, 0x3c,
	0x53, 0xeb, 0x8f, 0xfd, 0xbe, 0x77, 0xf8, 0x2f, 0x5e, 0x9a, 0x3d, 0x79, 0xd1, 0xdd, 0x67, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0x74, 0xf7, 0xe3, 0x67, 0x01, 0x00, 0x00,
}
