// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	CreateContactReq
	CreateContactRes
	ListContactsReq
	ListContactsRes
	Contact
	PhoneNumber
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneNumber_PhoneType int32

const (
	PhoneNumber_MOBILE PhoneNumber_PhoneType = 0
	PhoneNumber_HOME   PhoneNumber_PhoneType = 1
	PhoneNumber_WORK   PhoneNumber_PhoneType = 2
)

var PhoneNumber_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var PhoneNumber_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneNumber_PhoneType) String() string {
	return proto.EnumName(PhoneNumber_PhoneType_name, int32(x))
}
func (PhoneNumber_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type CreateContactReq struct {
	Name         string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email        string         `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNumbers []*PhoneNumber `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers" json:"phone_numbers,omitempty"`
}

func (m *CreateContactReq) Reset()                    { *m = CreateContactReq{} }
func (m *CreateContactReq) String() string            { return proto.CompactTextString(m) }
func (*CreateContactReq) ProtoMessage()               {}
func (*CreateContactReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateContactReq) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

type CreateContactRes struct {
	Contact *Contact `protobuf:"bytes,1,opt,name=contact" json:"contact,omitempty"`
}

func (m *CreateContactRes) Reset()                    { *m = CreateContactRes{} }
func (m *CreateContactRes) String() string            { return proto.CompactTextString(m) }
func (*CreateContactRes) ProtoMessage()               {}
func (*CreateContactRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateContactRes) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ListContactsReq struct {
}

func (m *ListContactsReq) Reset()                    { *m = ListContactsReq{} }
func (m *ListContactsReq) String() string            { return proto.CompactTextString(m) }
func (*ListContactsReq) ProtoMessage()               {}
func (*ListContactsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListContactsRes struct {
	Contacts []*Contact `protobuf:"bytes,1,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *ListContactsRes) Reset()                    { *m = ListContactsRes{} }
func (m *ListContactsRes) String() string            { return proto.CompactTextString(m) }
func (*ListContactsRes) ProtoMessage()               {}
func (*ListContactsRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListContactsRes) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type Contact struct {
	Name        string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email       string         `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNumber []*PhoneNumber `protobuf:"bytes,3,rep,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Contact) GetPhoneNumber() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type PhoneNumber struct {
	Number string                `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   PhoneNumber_PhoneType `protobuf:"varint,2,opt,name=type,enum=api.PhoneNumber_PhoneType" json:"type,omitempty"`
}

func (m *PhoneNumber) Reset()                    { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()               {}
func (*PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*CreateContactReq)(nil), "api.CreateContactReq")
	proto.RegisterType((*CreateContactRes)(nil), "api.CreateContactRes")
	proto.RegisterType((*ListContactsReq)(nil), "api.ListContactsReq")
	proto.RegisterType((*ListContactsRes)(nil), "api.ListContactsRes")
	proto.RegisterType((*Contact)(nil), "api.Contact")
	proto.RegisterType((*PhoneNumber)(nil), "api.PhoneNumber")
	proto.RegisterEnum("api.PhoneNumber_PhoneType", PhoneNumber_PhoneType_name, PhoneNumber_PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PhoneBook service

type PhoneBookClient interface {
	CreateContact(ctx context.Context, in *CreateContactReq, opts ...grpc.CallOption) (*CreateContactRes, error)
	ListContacts(ctx context.Context, in *ListContactsReq, opts ...grpc.CallOption) (*ListContactsRes, error)
}

type phoneBookClient struct {
	cc *grpc.ClientConn
}

func NewPhoneBookClient(cc *grpc.ClientConn) PhoneBookClient {
	return &phoneBookClient{cc}
}

func (c *phoneBookClient) CreateContact(ctx context.Context, in *CreateContactReq, opts ...grpc.CallOption) (*CreateContactRes, error) {
	out := new(CreateContactRes)
	err := grpc.Invoke(ctx, "/api.PhoneBook/CreateContact", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookClient) ListContacts(ctx context.Context, in *ListContactsReq, opts ...grpc.CallOption) (*ListContactsRes, error) {
	out := new(ListContactsRes)
	err := grpc.Invoke(ctx, "/api.PhoneBook/ListContacts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PhoneBook service

type PhoneBookServer interface {
	CreateContact(context.Context, *CreateContactReq) (*CreateContactRes, error)
	ListContacts(context.Context, *ListContactsReq) (*ListContactsRes, error)
}

func RegisterPhoneBookServer(s *grpc.Server, srv PhoneBookServer) {
	s.RegisterService(&_PhoneBook_serviceDesc, srv)
}

func _PhoneBook_CreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookServer).CreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PhoneBook/CreateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookServer).CreateContact(ctx, req.(*CreateContactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBook_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PhoneBook/ListContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookServer).ListContacts(ctx, req.(*ListContactsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PhoneBook",
	HandlerType: (*PhoneBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContact",
			Handler:    _PhoneBook_CreateContact_Handler,
		},
		{
			MethodName: "ListContacts",
			Handler:    _PhoneBook_ListContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0xb5, 0x80, 0x7c, 0xcc, 0x2e, 0xba, 0x4e, 0xd0, 0x6c, 0x38, 0x91, 0x1e, 0x0c, 0x89, 0x09,
	0x87, 0x25, 0x5e, 0x30, 0x5e, 0x20, 0x24, 0x1a, 0x41, 0x4c, 0x63, 0xe2, 0xd1, 0x14, 0xd2, 0x84,
	0x8d, 0xb2, 0x2d, 0xb4, 0x1e, 0xb8, 0x7a, 0xf0, 0x77, 0x1b, 0xba, 0x05, 0x97, 0x15, 0x0f, 0xde,
	0x66, 0xde, 0x7b, 0x9d, 0xd7, 0xd7, 0x0e, 0xd4, 0xb8, 0x8a, 0x3b, 0x6a, 0x25, 0x8d, 0xc4, 0x22,
	0x57, 0x31, 0xd5, 0x10, 0x0c, 0x56, 0x82, 0x1b, 0x31, 0x90, 0x89, 0xe1, 0x33, 0xc3, 0xc4, 0x12,
	0x11, 0x4a, 0x09, 0x5f, 0x88, 0x90, 0xb4, 0x48, 0xbb, 0xc6, 0x6c, 0x8d, 0x0d, 0x38, 0x16, 0x0b,
	0x1e, 0xbf, 0x87, 0x05, 0x0b, 0xa6, 0x0d, 0x5e, 0x43, 0x5d, 0xcd, 0x65, 0x22, 0x5e, 0x93, 0x8f,
	0xc5, 0x54, 0xac, 0x74, 0x58, 0x6c, 0x15, 0xdb, 0x5e, 0x14, 0x74, 0x36, 0x2e, 0x4f, 0x1b, 0xe6,
	0xd1, 0x12, 0xcc, 0x57, 0x3f, 0x8d, 0xa6, 0xbd, 0x5f, 0xa6, 0x1a, 0x2f, 0xa1, 0x32, 0x4b, 0x3b,
	0xeb, 0xeb, 0x45, 0xbe, 0x1d, 0xb2, 0x55, 0x6c, 0x49, 0x7a, 0x06, 0xa7, 0xa3, 0x58, 0x1b, 0x87,
	0x6b, 0x26, 0x96, 0xf4, 0x26, 0x0f, 0x69, 0x6c, 0x43, 0xd5, 0x1d, 0xd0, 0x21, 0xb1, 0x77, 0xda,
	0x1f, 0xb7, 0x63, 0xe9, 0x1c, 0x2a, 0x0e, 0xfc, 0x47, 0xee, 0x2e, 0xf8, 0xd9, 0xdc, 0x7f, 0xc6,
	0xf6, 0x32, 0xb1, 0xe9, 0x27, 0x01, 0x2f, 0x43, 0xe2, 0x05, 0x94, 0xdd, 0xf1, 0xd4, 0xd0, 0x75,
	0xd8, 0x81, 0x92, 0x59, 0x2b, 0x61, 0x1d, 0x4f, 0xa2, 0x66, 0x7e, 0x68, 0x5a, 0x3f, 0xaf, 0x95,
	0x60, 0x56, 0x47, 0xaf, 0xa0, 0xb6, 0x83, 0x10, 0xa0, 0x3c, 0x9e, 0xf4, 0xef, 0x47, 0xc3, 0xe0,
	0x08, 0xab, 0x50, 0xba, 0x9b, 0x8c, 0x87, 0x01, 0xd9, 0x54, 0x2f, 0x13, 0xf6, 0x10, 0x14, 0xa2,
	0x2f, 0xe2, 0xd4, 0x7d, 0x29, 0xdf, 0xf0, 0x16, 0xea, 0x7b, 0x1f, 0x81, 0xe7, 0xe9, 0x2b, 0xe5,
	0x36, 0xa2, 0x79, 0x10, 0xd6, 0xd8, 0x03, 0x3f, 0xfb, 0xf0, 0xd8, 0xb0, 0xb2, 0xdc, 0xf7, 0x34,
	0x0f, 0xa1, 0x7a, 0x5a, 0xb6, 0x4b, 0xd8, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x41, 0xc2,
	0x93, 0x91, 0x02, 0x00, 0x00,
}
