/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.api.Contact', null, global);
goog.exportSymbol('proto.api.CreateContactReq', null, global);
goog.exportSymbol('proto.api.CreateContactRes', null, global);
goog.exportSymbol('proto.api.DeleteContactReq', null, global);
goog.exportSymbol('proto.api.DeleteContactRes', null, global);
goog.exportSymbol('proto.api.ListContactsReq', null, global);
goog.exportSymbol('proto.api.ListContactsRes', null, global);
goog.exportSymbol('proto.api.PhoneNumber', null, global);
goog.exportSymbol('proto.api.PhoneNumber.PhoneType', null, global);
goog.exportSymbol('proto.api.ShowContactReq', null, global);
goog.exportSymbol('proto.api.ShowContactRes', null, global);
goog.exportSymbol('proto.api.UpdateContactReq', null, global);
goog.exportSymbol('proto.api.UpdateContactRes', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.CreateContactReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.CreateContactReq.repeatedFields_, null);
};
goog.inherits(proto.api.CreateContactReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.CreateContactReq.displayName = 'proto.api.CreateContactReq';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.CreateContactReq.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.CreateContactReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.CreateContactReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.CreateContactReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.CreateContactReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    phoneNumbersList: jspb.Message.toObjectList(msg.getPhoneNumbersList(),
    proto.api.PhoneNumber.toObject, includeInstance),
    home: (f = msg.getHome()) && proto.api.PhoneNumber.toObject(includeInstance, f),
    mobile: (f = msg.getMobile()) && proto.api.PhoneNumber.toObject(includeInstance, f),
    work: (f = msg.getWork()) && proto.api.PhoneNumber.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.CreateContactReq}
 */
proto.api.CreateContactReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.CreateContactReq;
  return proto.api.CreateContactReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.CreateContactReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.CreateContactReq}
 */
proto.api.CreateContactReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.addPhoneNumbers(value);
      break;
    case 4:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setHome(value);
      break;
    case 5:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setMobile(value);
      break;
    case 6:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setWork(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.CreateContactReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.CreateContactReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.CreateContactReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.CreateContactReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getPhoneNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getHome();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getMobile();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getWork();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.api.CreateContactReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.CreateContactReq.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.api.CreateContactReq.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.CreateContactReq.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated PhoneNumber phone_numbers = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.api.PhoneNumber>}
 */
proto.api.CreateContactReq.prototype.getPhoneNumbersList = function() {
  return /** @type{!Array.<!proto.api.PhoneNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.PhoneNumber, 3));
};


/** @param {!Array.<!proto.api.PhoneNumber>} value */
proto.api.CreateContactReq.prototype.setPhoneNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.PhoneNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.PhoneNumber}
 */
proto.api.CreateContactReq.prototype.addPhoneNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.PhoneNumber, opt_index);
};


proto.api.CreateContactReq.prototype.clearPhoneNumbersList = function() {
  this.setPhoneNumbersList([]);
};


/**
 * optional PhoneNumber home = 4;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.CreateContactReq.prototype.getHome = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 4));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.CreateContactReq.prototype.setHome = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.api.CreateContactReq.prototype.clearHome = function() {
  this.setHome(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.CreateContactReq.prototype.hasHome = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PhoneNumber mobile = 5;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.CreateContactReq.prototype.getMobile = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 5));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.CreateContactReq.prototype.setMobile = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.api.CreateContactReq.prototype.clearMobile = function() {
  this.setMobile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.CreateContactReq.prototype.hasMobile = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional PhoneNumber work = 6;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.CreateContactReq.prototype.getWork = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 6));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.CreateContactReq.prototype.setWork = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.api.CreateContactReq.prototype.clearWork = function() {
  this.setWork(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.CreateContactReq.prototype.hasWork = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.CreateContactRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.CreateContactRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.CreateContactRes.displayName = 'proto.api.CreateContactRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.CreateContactRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.CreateContactRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.CreateContactRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.CreateContactRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contact: (f = msg.getContact()) && proto.api.Contact.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.CreateContactRes}
 */
proto.api.CreateContactRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.CreateContactRes;
  return proto.api.CreateContactRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.CreateContactRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.CreateContactRes}
 */
proto.api.CreateContactRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.Contact;
      reader.readMessage(value,proto.api.Contact.deserializeBinaryFromReader);
      msg.setContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.CreateContactRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.CreateContactRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.CreateContactRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.CreateContactRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getContact();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * optional Contact contact = 1;
 * @return {?proto.api.Contact}
 */
proto.api.CreateContactRes.prototype.getContact = function() {
  return /** @type{?proto.api.Contact} */ (
    jspb.Message.getWrapperField(this, proto.api.Contact, 1));
};


/** @param {?proto.api.Contact|undefined} value */
proto.api.CreateContactRes.prototype.setContact = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.api.CreateContactRes.prototype.clearContact = function() {
  this.setContact(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.CreateContactRes.prototype.hasContact = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ListContactsReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.ListContactsReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.ListContactsReq.displayName = 'proto.api.ListContactsReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ListContactsReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ListContactsReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ListContactsReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.ListContactsReq.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ListContactsReq}
 */
proto.api.ListContactsReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ListContactsReq;
  return proto.api.ListContactsReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ListContactsReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ListContactsReq}
 */
proto.api.ListContactsReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.ListContactsReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ListContactsReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ListContactsReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ListContactsReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ListContactsRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.ListContactsRes.repeatedFields_, null);
};
goog.inherits(proto.api.ListContactsRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.ListContactsRes.displayName = 'proto.api.ListContactsRes';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.ListContactsRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ListContactsRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ListContactsRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ListContactsRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.ListContactsRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contactsList: jspb.Message.toObjectList(msg.getContactsList(),
    proto.api.Contact.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ListContactsRes}
 */
proto.api.ListContactsRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ListContactsRes;
  return proto.api.ListContactsRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ListContactsRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ListContactsRes}
 */
proto.api.ListContactsRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.Contact;
      reader.readMessage(value,proto.api.Contact.deserializeBinaryFromReader);
      msg.addContacts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.ListContactsRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ListContactsRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ListContactsRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ListContactsRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getContactsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.api.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Contact contacts = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.api.Contact>}
 */
proto.api.ListContactsRes.prototype.getContactsList = function() {
  return /** @type{!Array.<!proto.api.Contact>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.Contact, 1));
};


/** @param {!Array.<!proto.api.Contact>} value */
proto.api.ListContactsRes.prototype.setContactsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.Contact=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.Contact}
 */
proto.api.ListContactsRes.prototype.addContacts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.Contact, opt_index);
};


proto.api.ListContactsRes.prototype.clearContactsList = function() {
  this.setContactsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.DeleteContactReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.DeleteContactReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.DeleteContactReq.displayName = 'proto.api.DeleteContactReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.DeleteContactReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.DeleteContactReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.DeleteContactReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.DeleteContactReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.DeleteContactReq}
 */
proto.api.DeleteContactReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.DeleteContactReq;
  return proto.api.DeleteContactReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.DeleteContactReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.DeleteContactReq}
 */
proto.api.DeleteContactReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.DeleteContactReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.DeleteContactReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.DeleteContactReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.DeleteContactReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.api.DeleteContactReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.DeleteContactReq.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.DeleteContactRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.DeleteContactRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.DeleteContactRes.displayName = 'proto.api.DeleteContactRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.DeleteContactRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.DeleteContactRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.DeleteContactRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.DeleteContactRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contact: (f = msg.getContact()) && proto.api.Contact.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.DeleteContactRes}
 */
proto.api.DeleteContactRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.DeleteContactRes;
  return proto.api.DeleteContactRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.DeleteContactRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.DeleteContactRes}
 */
proto.api.DeleteContactRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.Contact;
      reader.readMessage(value,proto.api.Contact.deserializeBinaryFromReader);
      msg.setContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.DeleteContactRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.DeleteContactRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.DeleteContactRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.DeleteContactRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getContact();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * optional Contact contact = 1;
 * @return {?proto.api.Contact}
 */
proto.api.DeleteContactRes.prototype.getContact = function() {
  return /** @type{?proto.api.Contact} */ (
    jspb.Message.getWrapperField(this, proto.api.Contact, 1));
};


/** @param {?proto.api.Contact|undefined} value */
proto.api.DeleteContactRes.prototype.setContact = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.api.DeleteContactRes.prototype.clearContact = function() {
  this.setContact(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.DeleteContactRes.prototype.hasContact = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ShowContactReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.ShowContactReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.ShowContactReq.displayName = 'proto.api.ShowContactReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ShowContactReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ShowContactReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ShowContactReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.ShowContactReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ShowContactReq}
 */
proto.api.ShowContactReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ShowContactReq;
  return proto.api.ShowContactReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ShowContactReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ShowContactReq}
 */
proto.api.ShowContactReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.ShowContactReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ShowContactReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ShowContactReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ShowContactReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.api.ShowContactReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.ShowContactReq.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ShowContactRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.ShowContactRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.ShowContactRes.displayName = 'proto.api.ShowContactRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ShowContactRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ShowContactRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ShowContactRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.ShowContactRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contact: (f = msg.getContact()) && proto.api.Contact.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ShowContactRes}
 */
proto.api.ShowContactRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ShowContactRes;
  return proto.api.ShowContactRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ShowContactRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ShowContactRes}
 */
proto.api.ShowContactRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.Contact;
      reader.readMessage(value,proto.api.Contact.deserializeBinaryFromReader);
      msg.setContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.ShowContactRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ShowContactRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ShowContactRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ShowContactRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getContact();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * optional Contact contact = 1;
 * @return {?proto.api.Contact}
 */
proto.api.ShowContactRes.prototype.getContact = function() {
  return /** @type{?proto.api.Contact} */ (
    jspb.Message.getWrapperField(this, proto.api.Contact, 1));
};


/** @param {?proto.api.Contact|undefined} value */
proto.api.ShowContactRes.prototype.setContact = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.api.ShowContactRes.prototype.clearContact = function() {
  this.setContact(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.ShowContactRes.prototype.hasContact = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.UpdateContactReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.UpdateContactReq.repeatedFields_, null);
};
goog.inherits(proto.api.UpdateContactReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.UpdateContactReq.displayName = 'proto.api.UpdateContactReq';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.UpdateContactReq.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.UpdateContactReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.UpdateContactReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.UpdateContactReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.UpdateContactReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    phoneNumbersList: jspb.Message.toObjectList(msg.getPhoneNumbersList(),
    proto.api.PhoneNumber.toObject, includeInstance),
    home: (f = msg.getHome()) && proto.api.PhoneNumber.toObject(includeInstance, f),
    mobile: (f = msg.getMobile()) && proto.api.PhoneNumber.toObject(includeInstance, f),
    work: (f = msg.getWork()) && proto.api.PhoneNumber.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.UpdateContactReq}
 */
proto.api.UpdateContactReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.UpdateContactReq;
  return proto.api.UpdateContactReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.UpdateContactReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.UpdateContactReq}
 */
proto.api.UpdateContactReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.addPhoneNumbers(value);
      break;
    case 4:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setHome(value);
      break;
    case 5:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setMobile(value);
      break;
    case 6:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setWork(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.UpdateContactReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.UpdateContactReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.UpdateContactReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.UpdateContactReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getPhoneNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getHome();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getMobile();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getWork();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.api.UpdateContactReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.UpdateContactReq.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.api.UpdateContactReq.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.UpdateContactReq.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated PhoneNumber phone_numbers = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.api.PhoneNumber>}
 */
proto.api.UpdateContactReq.prototype.getPhoneNumbersList = function() {
  return /** @type{!Array.<!proto.api.PhoneNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.PhoneNumber, 3));
};


/** @param {!Array.<!proto.api.PhoneNumber>} value */
proto.api.UpdateContactReq.prototype.setPhoneNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.PhoneNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.PhoneNumber}
 */
proto.api.UpdateContactReq.prototype.addPhoneNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.PhoneNumber, opt_index);
};


proto.api.UpdateContactReq.prototype.clearPhoneNumbersList = function() {
  this.setPhoneNumbersList([]);
};


/**
 * optional PhoneNumber home = 4;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.UpdateContactReq.prototype.getHome = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 4));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.UpdateContactReq.prototype.setHome = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.api.UpdateContactReq.prototype.clearHome = function() {
  this.setHome(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.UpdateContactReq.prototype.hasHome = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PhoneNumber mobile = 5;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.UpdateContactReq.prototype.getMobile = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 5));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.UpdateContactReq.prototype.setMobile = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.api.UpdateContactReq.prototype.clearMobile = function() {
  this.setMobile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.UpdateContactReq.prototype.hasMobile = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional PhoneNumber work = 6;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.UpdateContactReq.prototype.getWork = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 6));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.UpdateContactReq.prototype.setWork = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.api.UpdateContactReq.prototype.clearWork = function() {
  this.setWork(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.UpdateContactReq.prototype.hasWork = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.UpdateContactRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.UpdateContactRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.UpdateContactRes.displayName = 'proto.api.UpdateContactRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.UpdateContactRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.UpdateContactRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.UpdateContactRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.UpdateContactRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contact: (f = msg.getContact()) && proto.api.Contact.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.UpdateContactRes}
 */
proto.api.UpdateContactRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.UpdateContactRes;
  return proto.api.UpdateContactRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.UpdateContactRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.UpdateContactRes}
 */
proto.api.UpdateContactRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.Contact;
      reader.readMessage(value,proto.api.Contact.deserializeBinaryFromReader);
      msg.setContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.UpdateContactRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.UpdateContactRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.UpdateContactRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.UpdateContactRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getContact();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * optional Contact contact = 1;
 * @return {?proto.api.Contact}
 */
proto.api.UpdateContactRes.prototype.getContact = function() {
  return /** @type{?proto.api.Contact} */ (
    jspb.Message.getWrapperField(this, proto.api.Contact, 1));
};


/** @param {?proto.api.Contact|undefined} value */
proto.api.UpdateContactRes.prototype.setContact = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.api.UpdateContactRes.prototype.clearContact = function() {
  this.setContact(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.UpdateContactRes.prototype.hasContact = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.Contact = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.Contact.repeatedFields_, null);
};
goog.inherits(proto.api.Contact, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.Contact.displayName = 'proto.api.Contact';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.Contact.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.Contact.prototype.toObject = function(opt_includeInstance) {
  return proto.api.Contact.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.Contact} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.Contact.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    phoneNumbersList: jspb.Message.toObjectList(msg.getPhoneNumbersList(),
    proto.api.PhoneNumber.toObject, includeInstance),
    home: (f = msg.getHome()) && proto.api.PhoneNumber.toObject(includeInstance, f),
    mobile: (f = msg.getMobile()) && proto.api.PhoneNumber.toObject(includeInstance, f),
    work: (f = msg.getWork()) && proto.api.PhoneNumber.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.Contact}
 */
proto.api.Contact.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.Contact;
  return proto.api.Contact.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.Contact} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.Contact}
 */
proto.api.Contact.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.addPhoneNumbers(value);
      break;
    case 4:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setHome(value);
      break;
    case 5:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setMobile(value);
      break;
    case 6:
      var value = new proto.api.PhoneNumber;
      reader.readMessage(value,proto.api.PhoneNumber.deserializeBinaryFromReader);
      msg.setWork(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.Contact} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.Contact.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.Contact.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.Contact.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getPhoneNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getHome();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getMobile();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
  f = this.getWork();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.api.PhoneNumber.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.api.Contact.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.Contact.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.api.Contact.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.Contact.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated PhoneNumber phone_numbers = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.api.PhoneNumber>}
 */
proto.api.Contact.prototype.getPhoneNumbersList = function() {
  return /** @type{!Array.<!proto.api.PhoneNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.PhoneNumber, 3));
};


/** @param {!Array.<!proto.api.PhoneNumber>} value */
proto.api.Contact.prototype.setPhoneNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.PhoneNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.PhoneNumber}
 */
proto.api.Contact.prototype.addPhoneNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.PhoneNumber, opt_index);
};


proto.api.Contact.prototype.clearPhoneNumbersList = function() {
  this.setPhoneNumbersList([]);
};


/**
 * optional PhoneNumber home = 4;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.Contact.prototype.getHome = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 4));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.Contact.prototype.setHome = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.api.Contact.prototype.clearHome = function() {
  this.setHome(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.Contact.prototype.hasHome = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PhoneNumber mobile = 5;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.Contact.prototype.getMobile = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 5));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.Contact.prototype.setMobile = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.api.Contact.prototype.clearMobile = function() {
  this.setMobile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.Contact.prototype.hasMobile = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional PhoneNumber work = 6;
 * @return {?proto.api.PhoneNumber}
 */
proto.api.Contact.prototype.getWork = function() {
  return /** @type{?proto.api.PhoneNumber} */ (
    jspb.Message.getWrapperField(this, proto.api.PhoneNumber, 6));
};


/** @param {?proto.api.PhoneNumber|undefined} value */
proto.api.Contact.prototype.setWork = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.api.Contact.prototype.clearWork = function() {
  this.setWork(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.Contact.prototype.hasWork = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.PhoneNumber = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.PhoneNumber, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.PhoneNumber.displayName = 'proto.api.PhoneNumber';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.PhoneNumber.prototype.toObject = function(opt_includeInstance) {
  return proto.api.PhoneNumber.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.PhoneNumber} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.PhoneNumber.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.PhoneNumber}
 */
proto.api.PhoneNumber.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.PhoneNumber;
  return proto.api.PhoneNumber.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.PhoneNumber} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.PhoneNumber}
 */
proto.api.PhoneNumber.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {!proto.api.PhoneNumber.PhoneType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.api.PhoneNumber} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.PhoneNumber.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.PhoneNumber.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.PhoneNumber.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string number = 1;
 * @return {string}
 */
proto.api.PhoneNumber.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.PhoneNumber.prototype.setNumber = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional PhoneType type = 2;
 * @return {!proto.api.PhoneNumber.PhoneType}
 */
proto.api.PhoneNumber.prototype.getType = function() {
  return /** @type {!proto.api.PhoneNumber.PhoneType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.api.PhoneNumber.PhoneType} value */
proto.api.PhoneNumber.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.api.PhoneNumber.PhoneType = {
  MOBILE: 0,
  HOME: 1,
  WORK: 2
};

goog.object.extend(exports, proto.api);
