/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github.com_iheanyi_grpc$phonebook_phonebook_pb = require('./github.com/iheanyi/grpc-phonebook/phonebook_pb.js');
goog.exportSymbol('proto.api.CreateContactReq', null, global);
goog.exportSymbol('proto.api.CreateContactRes', null, global);
goog.exportSymbol('proto.api.ListContactsReq', null, global);
goog.exportSymbol('proto.api.ListContactsRes', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.CreateContactReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.CreateContactReq.repeatedFields_, null);
};
goog.inherits(proto.api.CreateContactReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.CreateContactReq.displayName = 'proto.api.CreateContactReq';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.CreateContactReq.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.CreateContactReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.CreateContactReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.CreateContactReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.CreateContactReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    phoneNumbersList: jspb.Message.toObjectList(msg.getPhoneNumbersList(),
    github.com_iheanyi_grpc$phonebook_phonebook_pb.PhoneNumber.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.CreateContactReq}
 */
proto.api.CreateContactReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.CreateContactReq;
  return proto.api.CreateContactReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.CreateContactReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.CreateContactReq}
 */
proto.api.CreateContactReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = new github.com_iheanyi_grpc$phonebook_phonebook_pb.PhoneNumber;
      reader.readMessage(value,github.com_iheanyi_grpc$phonebook_phonebook_pb.PhoneNumber.deserializeBinaryFromReader);
      msg.addPhoneNumbers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.CreateContactReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.CreateContactReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.CreateContactReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.CreateContactReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPhoneNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      github.com_iheanyi_grpc$phonebook_phonebook_pb.PhoneNumber.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.api.CreateContactReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.api.CreateContactReq.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.api.CreateContactReq.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.api.CreateContactReq.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated grpc_phonebook.PhoneNumber phone_numbers = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.grpc_phonebook.PhoneNumber>}
 */
proto.api.CreateContactReq.prototype.getPhoneNumbersList = function() {
  return /** @type{!Array.<!proto.grpc_phonebook.PhoneNumber>} */ (
    jspb.Message.getRepeatedWrapperField(this, github.com_iheanyi_grpc$phonebook_phonebook_pb.PhoneNumber, 3));
};


/** @param {!Array.<!proto.grpc_phonebook.PhoneNumber>} value */
proto.api.CreateContactReq.prototype.setPhoneNumbersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.grpc_phonebook.PhoneNumber=} opt_value
 * @param {number=} opt_index
 * @return {!proto.grpc_phonebook.PhoneNumber}
 */
proto.api.CreateContactReq.prototype.addPhoneNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.grpc_phonebook.PhoneNumber, opt_index);
};


proto.api.CreateContactReq.prototype.clearPhoneNumbersList = function() {
  this.setPhoneNumbersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.CreateContactRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.CreateContactRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.CreateContactRes.displayName = 'proto.api.CreateContactRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.CreateContactRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.CreateContactRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.CreateContactRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.CreateContactRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contact: (f = msg.getContact()) && github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.CreateContactRes}
 */
proto.api.CreateContactRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.CreateContactRes;
  return proto.api.CreateContactRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.CreateContactRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.CreateContactRes}
 */
proto.api.CreateContactRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact;
      reader.readMessage(value,github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact.deserializeBinaryFromReader);
      msg.setContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.CreateContactRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.CreateContactRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.CreateContactRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.CreateContactRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContact();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * optional grpc_phonebook.Contact contact = 1;
 * @return {?proto.grpc_phonebook.Contact}
 */
proto.api.CreateContactRes.prototype.getContact = function() {
  return /** @type{?proto.grpc_phonebook.Contact} */ (
    jspb.Message.getWrapperField(this, github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact, 1));
};


/** @param {?proto.grpc_phonebook.Contact|undefined} value */
proto.api.CreateContactRes.prototype.setContact = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.api.CreateContactRes.prototype.clearContact = function() {
  this.setContact(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.api.CreateContactRes.prototype.hasContact = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ListContactsReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.ListContactsReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.ListContactsReq.displayName = 'proto.api.ListContactsReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ListContactsReq.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ListContactsReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ListContactsReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.ListContactsReq.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ListContactsReq}
 */
proto.api.ListContactsReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ListContactsReq;
  return proto.api.ListContactsReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ListContactsReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ListContactsReq}
 */
proto.api.ListContactsReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ListContactsReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.ListContactsReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.ListContactsReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ListContactsReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.ListContactsRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.ListContactsRes.repeatedFields_, null);
};
goog.inherits(proto.api.ListContactsRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.api.ListContactsRes.displayName = 'proto.api.ListContactsRes';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.ListContactsRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.ListContactsRes.prototype.toObject = function(opt_includeInstance) {
  return proto.api.ListContactsRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.ListContactsRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.api.ListContactsRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    contactsList: jspb.Message.toObjectList(msg.getContactsList(),
    github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.ListContactsRes}
 */
proto.api.ListContactsRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.ListContactsRes;
  return proto.api.ListContactsRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.ListContactsRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.ListContactsRes}
 */
proto.api.ListContactsRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact;
      reader.readMessage(value,github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact.deserializeBinaryFromReader);
      msg.addContacts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.ListContactsRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.ListContactsRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.ListContactsRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.api.ListContactsRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContactsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact.serializeBinaryToWriter
    );
  }
};


/**
 * repeated grpc_phonebook.Contact contacts = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.grpc_phonebook.Contact>}
 */
proto.api.ListContactsRes.prototype.getContactsList = function() {
  return /** @type{!Array.<!proto.grpc_phonebook.Contact>} */ (
    jspb.Message.getRepeatedWrapperField(this, github.com_iheanyi_grpc$phonebook_phonebook_pb.Contact, 1));
};


/** @param {!Array.<!proto.grpc_phonebook.Contact>} value */
proto.api.ListContactsRes.prototype.setContactsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.grpc_phonebook.Contact=} opt_value
 * @param {number=} opt_index
 * @return {!proto.grpc_phonebook.Contact}
 */
proto.api.ListContactsRes.prototype.addContacts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.grpc_phonebook.Contact, opt_index);
};


proto.api.ListContactsRes.prototype.clearContactsList = function() {
  this.setContactsList([]);
};


goog.object.extend(exports, proto.api);
